### ISSUE TITLE
Doesn't work on IE 11

### ISSUE THREAD

**Issue by PavelHasala** [bukinoshita/detect-browser-language#1]
Breaks down on module export with `Syntax error `

```js
module.exports = () =>
  (navigator.languages && navigator.languages[0]) ||
  navigator.language ||
  navigator.userLanguage
```

I know it is trendy to just ditch everything that is older than 3 months, but unfortunately a lot of users are still on windows 7 using IE 11.

**Comment by joh-klein** [comment]
fixed with #3
